spring.application.name=proyecto-inversiones
spring.data.mongodb.uri=mongodb+srv://admin:admin@inversiones-cluster.rqbmrxe.mongodb.net/inversiones-DB
spring.data.mongodb.database=inversiones-DB
server.port=8080